spring.application.name=api-gateway
server.port=8080

# Eureka Client Configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Spring Cloud Gateway Routes
# Redirigir /api/auth/** al microservicio auth-service
spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=lb://auth-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/auth/**

# Redirigir /api/tareas/** al microservicio task-service
spring.cloud.gateway.routes[1].id=task-service
spring.cloud.gateway.routes[1].uri=lb://task-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/tareas/**

# Configuración CORS Global
spring.cloud.gateway.globalcors.add-to-simple-url-handler-mapping=true
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOrigins=http://localhost:4200
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedHeaders=*

spring.cloud.compatibility-verifier.enabled=false


